const orders = [
    {
        name: 'David Perry',
        productId: '#01345',
        productName: 'LED Television',
        quantity: '03',
        status: 1,
        date: '2019:09:19',
        id: 1,
    },
    {
        name: 'Jonathan',
        productId: '#05345',
        productName: 'Apple iPhone XR',
        quantity: '2',
        status: 0,
        date: '2019:09:03',
        id: 2,
    },
    {
        name: 'John Kate',
        productId: '#04523',
        productName: 'Dior Homme',
        quantity: '10',
        status: 2,
        date: '2019:09:11',
        id: 3,
    },
    {
        name: 'Virginia Gomes',
        productId: '#90567',
        productName: 'Apple iPhone XR',
        quantity: '6',
        status: 0,
        date: '2019:09:17',
        id: 4,
    },
    {
        name: 'Virginia',
        productId: '#90567',
        productName: 'iPhone XR',
        quantity: '6',
        status: 1,
        date: '2019:09:17',
        id: 5,
    },
];
export default orders;
